[build]
publish = "."

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/interns"
to = "/interns.html"
status = 200

[[headers]]
for = "/*"

  [headers.values]
  X-Content-Type-Options = "nosniff"
